//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shaders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shaders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VesselViewer.Properties.Shaders", typeof(Shaders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shader &quot;Hidden/SlinDev/Desktop/PostProcessing/FXAA&quot;
        ///{
        ///    Properties
        ///    {
        ///        _MainTex (&quot;Base (RGB)&quot;, RECT) = &quot;white&quot; {}
        ///    }
        ///
        ///    SubShader
        ///    {
        ///        Pass
        ///        {
        ///            ZTest Always
        ///            Cull Off
        ///            ZWrite Off
        ///            Fog { Mode off }
        ///    
        ///            Program &quot;vp&quot; {
        ///// Vertex combos: 1
        /////   d3d9 - ALU: 7 to 7
        /////   d3d11 - ALU: 1 to 1, TEX: 0 to 0, FLOW: 1 to 1
        ///SubProgram &quot;opengl &quot; {
        ///Keywords { }
        ///&quot;!!GLSL
        ///#ifdef VERTEX
        ///varying vec4 xlv_TEXCOORD0;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShaderFXAA {
            get {
                return ResourceManager.GetString("ShaderFXAA", resourceCulture);
            }
        }
    }
}
